name: Primedian-iOS
options:
  findCarthageFrameworks: true
targets:
  Primedian-iOS:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: Primedian-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.christopherszatmary.Primedian-iOS
    dependencies:
      - carthage: TinyConstraints
  Primedian-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources: Primedian-iOSTests
    dependencies:
      - target: Primedian-iOS
      - carthage: Quick
      - carthage: Nimble
  Primedian-iOSUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: Primedian-iOSUITests
    dependencies:
      - target: Primedian-iOS
      - carthage: Quick
      - carthage: Nimble
schemes:
  Primedian-iOS:
    build:
      targets:
        Primedian-iOS: all
        Primedian-iOSTests: [test]
        Primedian-iOSUITests: [test]
    run:
      environmentVariables:
        PRIMEDIAN_API_BASE_URL: "http://localhost:8000"
    test:
      gatherCoverageData: true
      targets:
        - name: Primedian-iOSTests
        - name: Primedian-iOSUITests
